package Clases;

import static Clases.Principal.rHash;
import arbolbin.ArbolBinario;
import arbolbin.NodoArbol;
import arbolbin.TablasHash;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import listas.GuardaArchivos;
import listas.Multilistas;
import static listas.Multilistas.busca;
import listas.Nodo;
import proyu3u4.AgregaCar;

public class AgregarCarr extends javax.swing.JFrame
{

    public static String car = "";
    String label[] = new String[2];

    /**
     * Creates new form VentanaCarrera
     */
    public AgregarCarr()
    {
        initComponents();
    setIconImage(new ImageIcon(getClass().getResource("../Imagenes/tecnm.png")).getImage());
        actualizarUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        carComboBox = new javax.swing.JComboBox<>();
        cancelarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        claveLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();
        claveTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        jefeTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tecnologico Nacional de Mexico");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carComboBox.setBackground(new java.awt.Color(153, 153, 153));
        carComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        carComboBox.setForeground(new java.awt.Color(255, 255, 255));
        carComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        carComboBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                carComboBoxItemStateChanged(evt);
            }
        });
        carComboBox.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                carComboBoxMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                carComboBoxMousePressed(evt);
            }
        });
        getContentPane().add(carComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 210, 30));

        cancelarButton.setBackground(new java.awt.Color(153, 153, 153));
        cancelarButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarButton.setText("Atrás");
        cancelarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 435, 130, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar Carrera");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 280, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Selecciona Instituto:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 250, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO_TECNM_BLANCO (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        claveLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        claveLabel.setForeground(new java.awt.Color(255, 255, 255));
        claveLabel.setText("Clave de Carrera:");
        getContentPane().add(claveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Carrera:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jefe de Carrera:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 150, 40));

        aceptarButton.setBackground(new java.awt.Color(153, 153, 153));
        aceptarButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        aceptarButton.setForeground(new java.awt.Color(255, 255, 255));
        aceptarButton.setText("Aceptar");
        aceptarButton.setEnabled(false);
        aceptarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarButtonActionPerformed(evt);
            }
        });
        aceptarButton.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                aceptarButtonKeyPressed(evt);
            }
        });
        getContentPane().add(aceptarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 130, 40));

        claveTextField.setEnabled(false);
        claveTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                claveTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                claveTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(claveTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 290, 30));

        nombreTextField.setEnabled(false);
        nombreTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nombreTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombreTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 290, 30));

        jefeTextField.setEnabled(false);
        jefeTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jefeTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jefeTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(jefeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 290, 30));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Menu Principal");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 180, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura-madera-en-negro_2560x1600_xtrafondos.com.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarButtonActionPerformed
    {//GEN-HEADEREND:event_cancelarButtonActionPerformed
    JOptionPane.showMessageDialog(this, "Los cambios no Guardados se perderan", "ATENCION", JOptionPane.WARNING_MESSAGE);    
    MC v = new MC();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarButtonActionPerformed
    {//GEN-HEADEREND:event_aceptarButtonActionPerformed
        try
        {
            if (!claveTextField.getText().isEmpty() && !nombreTextField.getText().isEmpty() && !jefeTextField.getText().isEmpty())
            {
                String cve = claveTextField.getText();
                String nom = nombreTextField.getText();
                String boss = jefeTextField.getText();
                AgregaCar car = new AgregaCar(0, "", "");
                Object objCar = car.datos(Integer.parseInt(cve), nom, boss);
                Nodo c = new Nodo(objCar, nombreTextField.getText());
                String etiqueta[] = new String[2];
                etiqueta[0] = carComboBox.getSelectedItem().toString();
                etiqueta[1] = nombreTextField.getText();
                Nodo n1 = buscar(Principal.raiz, 0, etiqueta);
                Nodo ex = buscar(Principal.raiz, 0, etiqueta);
                Nodo aux = Multilistas.busca(Principal.raiz, etiqueta[0]);
                if (n1 != null && ex != null)
                {
                    if (n1.getEtiqueta().equalsIgnoreCase(ex.getEtiqueta()))
                    {
                        JOptionPane.showMessageDialog(null, "Carrera ya resgistrada con el mismo nombre");
                    } else
                    {

                        Principal.raiz = Multilistas.insertar(Principal.raiz, c, 0, etiqueta, aux);
                        //insercion en el arbol
                        NodoArbol ca = new NodoArbol(c.getEtiqueta().toLowerCase());
                        ca.setHilo(c);
                        Principal.rHash = TablasHash.inserta(Principal.rHash, ca, n1);
                        JOptionPane.showMessageDialog(null, "Carrera agregada");
                    }
                } else
                {

                    Principal.raiz = Multilistas.insertar(Principal.raiz, c, 0, etiqueta, aux);
                    //insercion en el arbol
                    NodoArbol ca = new NodoArbol(c.getEtiqueta().toLowerCase());
                    ca.setHilo(c);
                    Principal.rHash = TablasHash.inserta(Principal.rHash, ca, n1);
                    JOptionPane.showMessageDialog(null, "Carrera agregada");
                }
                actualizarUI();
                Principal v = new Principal();
                v.setVisible(true);
                this.dispose();
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, " Error !!!\n" + " Intente de nuevo");

        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void aceptarButtonKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aceptarButtonKeyPressed
    {//GEN-HEADEREND:event_aceptarButtonKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            aceptarButtonActionPerformed(null);
        }
    }//GEN-LAST:event_aceptarButtonKeyPressed

    private void carComboBoxMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_carComboBoxMouseClicked
    {//GEN-HEADEREND:event_carComboBoxMouseClicked

    }//GEN-LAST:event_carComboBoxMouseClicked

    private void carComboBoxMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_carComboBoxMousePressed
    {//GEN-HEADEREND:event_carComboBoxMousePressed

    }//GEN-LAST:event_carComboBoxMousePressed

    private void claveTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_claveTextFieldKeyTyped
    {//GEN-HEADEREND:event_claveTextFieldKeyTyped
        //Validaciones.validaEntero(evt);
        Validaciones.validaEntero(evt, 8, claveTextField.getText());
    }//GEN-LAST:event_claveTextFieldKeyTyped

    private void claveTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_claveTextFieldKeyPressed
    {//GEN-HEADEREND:event_claveTextFieldKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (validarCVacio(claveTextField))
            {
                CtrlInterfaz.cambia(nombreTextField);
            } else
            {
                JOptionPane.showMessageDialog(this, "No puede dejar este campo vacio", "ATENCION", JOptionPane.WARNING_MESSAGE);
                claveTextField.requestFocus();
            }
        }
    }//GEN-LAST:event_claveTextFieldKeyPressed

    private void carComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_carComboBoxItemStateChanged
    {//GEN-HEADEREND:event_carComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            if (carComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || carComboBox.getSelectedItem().toString().equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(null, "Seleccione una institucion\npara agregar carrera", "IMPORTANTE", JOptionPane.INFORMATION_MESSAGE);
                claveTextField.setEnabled(false);
            } else
            {
                CtrlInterfaz.cambia(claveTextField);
            }
        }
    }//GEN-LAST:event_carComboBoxItemStateChanged

    private void nombreTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreTextFieldKeyTyped
    {//GEN-HEADEREND:event_nombreTextFieldKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_nombreTextFieldKeyTyped

    private void nombreTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreTextFieldKeyPressed
    {//GEN-HEADEREND:event_nombreTextFieldKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (validarCVacio(nombreTextField))
            {
                CtrlInterfaz.cambia(jefeTextField);
            } else
            {
                JOptionPane.showMessageDialog(this, "No puede dejar este campo vacio", "ATENCION", JOptionPane.WARNING_MESSAGE);
                nombreTextField.requestFocus();
            }
        }
    }//GEN-LAST:event_nombreTextFieldKeyPressed

    private void jefeTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jefeTextFieldKeyTyped
    {//GEN-HEADEREND:event_jefeTextFieldKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jefeTextFieldKeyTyped

    private void jefeTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jefeTextFieldKeyPressed
    {//GEN-HEADEREND:event_jefeTextFieldKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (validarCVacio(jefeTextField))
            {
                CtrlInterfaz.cambia(aceptarButton);
            } else
            {
                JOptionPane.showMessageDialog(this, "No puede dejar este campo vacio", "ATENCION", JOptionPane.WARNING_MESSAGE);
                jefeTextField.requestFocus();
            }
        }
    }//GEN-LAST:event_jefeTextFieldKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Principal v = new Principal();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        claveTextField.setText("");
        CtrlInterfaz.habilita(false, nombreTextField);
        claveTextField.requestFocus();
        nombreTextField.setText("");
        CtrlInterfaz.habilita(false, jefeTextField);
        jefeTextField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
    JOptionPane.showMessageDialog(this, "Los cambios no Guardados se perderan", "ATENCION", JOptionPane.WARNING_MESSAGE);    
    Principal v = new Principal();
        v.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
//    

    public static Nodo buscar(Nodo raiz, int nivel, String[] etiqueta)
    {
        if (nivel == etiqueta.length - 1)
        {
            Nodo aux1 = busca(raiz, etiqueta[nivel]);
            if (aux1 != null)
            {
                System.out.println("Lo encontre: " + aux1.getEtiqueta());
            }
            return aux1;
        } else
        {
            Nodo aux = busca(raiz, etiqueta[nivel]);
            if (aux == null)
            {
                System.out.println("No encontre el dato: " + etiqueta[nivel] + " del nivel " + nivel);
                return raiz;
            } else
            {
                return buscar(aux.getAbj(), nivel + 1, etiqueta);
            }
        }
    }

    public NodoArbol balanceo(NodoArbol raiz)
    {
        ArbolBinario ab = new ArbolBinario();
        return ab.balancear(raiz);
    }

    public String desp0(Nodo raiz, int nivel)
    {
        String s = "";
        if (raiz != null)
        {
            s = raiz.getEtiqueta();
            carComboBox.addItem(s);
            desp0(raiz.getSig(), 0);
        }
        return s;
    }

    public void actualizarUI()
    {
        GuardaArchivos.guardar(Principal.raiz, "Multilista.dat");
        GuardaArchivos.guardar(Principal.rHash, "TablaArbol.dat");
        desp0(Principal.raiz, 0);

    }

    public boolean validarCVacio(JTextField textField)
    {
        if (textField.getText().isEmpty())
        {
            return false;
        } else
        {
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AgregarCarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AgregarCarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AgregarCarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AgregarCarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AgregarCarr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JComboBox<String> carComboBox;
    private javax.swing.JLabel claveLabel;
    private javax.swing.JTextField claveTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jefeTextField;
    private javax.swing.JTextField nombreTextField;
    // End of variables declaration//GEN-END:variables

}
