package Clases;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import com.toedter.calendar.JDateChooser;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import listas.GuardaArchivos;
import listas.Multilistas;
import static listas.Multilistas.busca;
import listas.Nodo;
import proyu3u4.AgregaReu;
import proyu3u4.Carrera;
import proyu3u4.Reunion;

/**
 *
 * @author Daniel Alberto Hernandez Castrejon
 * @author Humberto Gonzalez Garduño
 * @author Oscar Lopez Fonseca
 */
public class AgregarReun extends javax.swing.JFrame
{

    String label[] = new String[2];
    String reu = "";

    /**
     * Creates new form VentanaReunion
     */
    public AgregarReun()
    {
        initComponents();
        actualizarUI();
        agregarPanel.setVisible(false);
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/tecnm.png")).getImage());
        ((JTextField) this.fechaCalendar.getDateEditor()).setEditable(false);
        // UpdateUI(VentanaP.raiz, UpdateLabel(), 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        insComboBox = new javax.swing.JComboBox<>();
        cancelarButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        carComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        agregarPanel = new javax.swing.JPanel();
        fechaLabel = new javax.swing.JLabel();
        motLabel = new javax.swing.JLabel();
        flioLabel = new javax.swing.JLabel();
        fechaCalendar = new com.toedter.calendar.JDateChooser();
        motTextField = new javax.swing.JTextField();
        folTextField = new javax.swing.JTextField();
        Cancelar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REUNIONES DE ACADEMIA");
        setBackground(new java.awt.Color(0, 102, 204));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insComboBox.setBackground(new java.awt.Color(153, 153, 153));
        insComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        insComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        insComboBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                insComboBoxItemStateChanged(evt);
            }
        });
        getContentPane().add(insComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 200, 30));

        cancelarButton.setBackground(new java.awt.Color(153, 153, 153));
        cancelarButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarButton.setText("Limpiar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarButtonActionPerformed(evt);
            }
        });
        cancelarButton.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cancelarButtonKeyPressed(evt);
            }
        });
        getContentPane().add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 140, 40));

        aceptarButton.setBackground(new java.awt.Color(153, 153, 153));
        aceptarButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        aceptarButton.setForeground(new java.awt.Color(255, 255, 255));
        aceptarButton.setText("Aceptar");
        aceptarButton.setEnabled(false);
        aceptarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarButtonActionPerformed(evt);
            }
        });
        aceptarButton.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                aceptarButtonKeyPressed(evt);
            }
        });
        getContentPane().add(aceptarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 140, 60));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Institucion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        carComboBox.setBackground(new java.awt.Color(153, 153, 153));
        carComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        carComboBox.setForeground(new java.awt.Color(255, 255, 255));
        carComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        carComboBox.setEnabled(false);
        carComboBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                carComboBoxItemStateChanged(evt);
            }
        });
        getContentPane().add(carComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 200, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Carrera:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 405, 130, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO_TECNM_BLANCO (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agregar Reunion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        agregarPanel.setBackground(new java.awt.Color(102, 102, 102));

        fechaLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaLabel.setText("Fecha:");

        motLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        motLabel.setForeground(new java.awt.Color(255, 255, 255));
        motLabel.setText("Motivo:");

        flioLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        flioLabel.setForeground(new java.awt.Color(255, 255, 255));
        flioLabel.setText("Folio:");

        fechaCalendar.setForeground(new java.awt.Color(153, 153, 153));
        fechaCalendar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                fechaCalendarMouseClicked(evt);
            }
        });
        fechaCalendar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                fechaCalendarKeyPressed(evt);
            }
        });

        motTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                motTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                motTextFieldKeyTyped(evt);
            }
        });

        folTextField.setEnabled(false);
        folTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                folTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                folTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout agregarPanelLayout = new javax.swing.GroupLayout(agregarPanel);
        agregarPanel.setLayout(agregarPanelLayout);
        agregarPanelLayout.setHorizontalGroup(
            agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarPanelLayout.createSequentialGroup()
                        .addComponent(fechaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(fechaCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agregarPanelLayout.createSequentialGroup()
                        .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motLabel)
                            .addComponent(flioLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(folTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(motTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        agregarPanelLayout.setVerticalGroup(
            agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaLabel)
                    .addComponent(fechaCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(agregarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flioLabel)
                    .addComponent(folTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(agregarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 390, 190));

        Cancelar1.setBackground(new java.awt.Color(153, 153, 153));
        Cancelar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Cancelar1.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar1.setText("Menu Principal");
        Cancelar1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Cancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura-madera-en-negro_2560x1600_xtrafondos.com.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarButtonActionPerformed
    {//GEN-HEADEREND:event_aceptarButtonActionPerformed
        try
        {
            if (!folTextField.getText().isEmpty() && !motTextField.getText().isEmpty() && comprobarFecha())
            {
                AgregaReu reu = new AgregaReu(0, "", "");
                Object objReu = reu.datos(Integer.parseInt(folTextField.getText()), motTextField.getText(), asignarFecha());
                Nodo reunion = new Nodo(objReu, folTextField.getText());
                String etiqueta[] = new String[3];
                etiqueta[0] = insComboBox.getSelectedItem().toString();
                etiqueta[1] = carComboBox.getSelectedItem().toString();
                etiqueta[2] = folTextField.getText();
                Nodo n1 = buscar(Principal.raiz, 0, etiqueta);
                Nodo ex = buscar(Principal.raiz, 0, etiqueta);
                if (n1 != null && ex != null)
                {
                    if (n1.getEtiqueta().equalsIgnoreCase(ex.getEtiqueta()))
                    {
                        JOptionPane.showMessageDialog(null, "Reunion ya resgistrada con el mismo folio");
                    } else
                    {
                        Principal.raiz = Multilistas.insertar(Principal.raiz, reunion, 0, etiqueta, null);
                        JOptionPane.showMessageDialog(null, "Reunion agregada");
                    }
                } else
                {
                    Principal.raiz = Multilistas.insertar(Principal.raiz, reunion, 0, etiqueta, null);
                    JOptionPane.showMessageDialog(null, "Reunion agregada");
                }

                folTextField.setText("");
                folTextField.requestFocus();
                motTextField.setText("");
                motTextField.requestFocus();
                ((JTextField) this.fechaCalendar.getDateEditor()).setText("");
                cambia(fechaCalendar);
                UpdateUI(Principal.raiz, etiqueta, 0);
            } else
            {
                //JOptionPane.showMessageDialog(null, " Error !!!\n" + " Intente de nuevo");
                cambia(fechaCalendar);
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, " Error !!!\n" + " Intente de nuevo");
            folTextField.setText("");
            motTextField.setText("");
            motTextField.requestFocus();
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void aceptarButtonKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aceptarButtonKeyPressed
    {//GEN-HEADEREND:event_aceptarButtonKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            aceptarButtonActionPerformed(null);
        }
    }//GEN-LAST:event_aceptarButtonKeyPressed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarButtonActionPerformed
    {//GEN-HEADEREND:event_cancelarButtonActionPerformed
        fechaCalendar.requestFocus();
        ((JTextField) this.fechaCalendar.getDateEditor()).setText("");
        folTextField.setText("");
        CtrlInterfaz.habilita(false, folTextField);
        cambia(fechaCalendar);
        motTextField.setText("");
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void cancelarButtonKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cancelarButtonKeyPressed
    {//GEN-HEADEREND:event_cancelarButtonKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            cancelarButtonActionPerformed(null);
        }
    }//GEN-LAST:event_cancelarButtonKeyPressed

    private void insComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_insComboBoxItemStateChanged
    {//GEN-HEADEREND:event_insComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            if (insComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || insComboBox.getSelectedItem().toString().equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(null, "Opcion Invalida");
                carComboBox.removeAllItems();
                carComboBox.addItem("Seleccione");
                carComboBox.setEnabled(false);
            } else
            {
                CtrlInterfaz.cambia(carComboBox);
                Nodo aux = Multilistas.busca(Principal.raiz, insComboBox.getSelectedItem().toString());
                carComboBox.removeAllItems();
                carComboBox.addItem("Seleccione");
                UpdateUI(Principal.raiz, UpdateLabel(aux.getEtiqueta()), 0);
            }
        }
    }//GEN-LAST:event_insComboBoxItemStateChanged

    private void carComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_carComboBoxItemStateChanged
    {//GEN-HEADEREND:event_carComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            if (carComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || carComboBox.getSelectedItem().toString().equalsIgnoreCase(""))
            {
                //JOptionPane.showMessageDialog(null, "Opcion Invalida");
                agregarPanel.setVisible(false);
            } else
            {
                agregarPanel.setVisible(true);
            }
        }
    }//GEN-LAST:event_carComboBoxItemStateChanged

    private void motTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_motTextFieldKeyTyped
    {//GEN-HEADEREND:event_motTextFieldKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_motTextFieldKeyTyped

    private void motTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_motTextFieldKeyPressed
    {//GEN-HEADEREND:event_motTextFieldKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (validarCVacio(motTextField))
            {
                CtrlInterfaz.cambia(folTextField);
            } else
            {
                JOptionPane.showMessageDialog(this, "No puede dejar este campo vacio", "ATENCION", JOptionPane.WARNING_MESSAGE);
                motTextField.requestFocus();
            }
        }
    }//GEN-LAST:event_motTextFieldKeyPressed

    private void fechaCalendarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fechaCalendarKeyPressed
    {//GEN-HEADEREND:event_fechaCalendarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            CtrlInterfaz.cambia(motTextField);
        }
    }//GEN-LAST:event_fechaCalendarKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Principal v = new Principal();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void folTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_folTextFieldKeyTyped
    {//GEN-HEADEREND:event_folTextFieldKeyTyped
        //Validaciones.validaEntero(evt);
        Validaciones.validaEntero(evt, 5, folTextField.getText());
    }//GEN-LAST:event_folTextFieldKeyTyped

    private void folTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_folTextFieldKeyPressed
    {//GEN-HEADEREND:event_folTextFieldKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (validarCVacio(folTextField))
            {
                CtrlInterfaz.cambia(aceptarButton);
            } else
            {
                JOptionPane.showMessageDialog(this, "No puede dejar este campo vacio", "ATENCION", JOptionPane.WARNING_MESSAGE);
                folTextField.requestFocus();
            }
        }
    }//GEN-LAST:event_folTextFieldKeyPressed

    private void fechaCalendarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_fechaCalendarMouseClicked
    {//GEN-HEADEREND:event_fechaCalendarMouseClicked

    }//GEN-LAST:event_fechaCalendarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
    JOptionPane.showMessageDialog(this, "Los cambios no Guardados se perderan", "ATENCION", JOptionPane.WARNING_MESSAGE);    
    MR v = new MR();
        v.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Cancelar1ActionPerformed
    {//GEN-HEADEREND:event_Cancelar1ActionPerformed
        // TODO add your handling code here:
    JOptionPane.showMessageDialog(this, "Los cambios no Guardados se perderan", "ATENCION", JOptionPane.WARNING_MESSAGE);   
    Principal pri=new Principal();
        pri.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Cancelar1ActionPerformed

    public String asignarFecha()
    {
        String s = "";
        s = Integer.toString(fechaCalendar.getCalendar().get(Calendar.DAY_OF_MONTH)) + "/";
        s += Integer.toString(fechaCalendar.getCalendar().get(Calendar.MONTH) + 1) + "/";
        s += Integer.toString(fechaCalendar.getCalendar().get(Calendar.YEAR));
        return s;
    }

    public boolean comprobarFecha()
    {
        Calendar fecha1 = GregorianCalendar.getInstance();
        if (fechaCalendar.getDate().after(fecha1.getTime()))
        {
            asignarFecha();
            return true;
        } else
        {
            JOptionPane.showMessageDialog(this, "   Fecha invalida seleccione una fecha\n    posterior a la de hoy", "\tERROR", JOptionPane.ERROR_MESSAGE);
            cambia(fechaCalendar);
            System.out.println("Fecha en el jdatechooser");
            System.out.println(fechaCalendar.getDate().toString());
            System.out.println("Fecha actual");
            System.out.println(fecha1.getTime().toString());
            return false;
        }
    }

    public void UpdateUI(Nodo raiz, String[] etiqueta, int nivel)
    {
        if (nivel == etiqueta.length - 1)
        {
            Nodo aux = raiz;
            String s = "";
            while (aux != null)
            {
                s = aux.getEtiqueta();
                carComboBox.addItem(s);
                aux = aux.getSig();
            }
        } else
        {
            Nodo aux = busca(raiz, etiqueta[nivel]);
            if (aux == null)
            {
                System.out.println("NO HAY REUNIONES");
            } else
            {
//                if (nivel == etiqueta.length - 2)
//                {
//                    Object obj = aux.getObj();
//                    dataPanel(obj);
//                }
                UpdateUI(aux.getAbj(), etiqueta, nivel + 1);
            }
        }
        GuardaArchivos.guardar(raiz, "Multilista.dat");
    }

//    public String[] UpdateLabel()
//    {
//        label[0] = VentanaP.tec;
//        label[1] = VentanaCarrera.car;
//        label[2] = "";
//        return label;
//    }
    public String[] UpdateLabel(String etq)
    {
        label[0] = etq;
        label[1] = "";
        return label;
    }

    public boolean validarCVacio(JTextField textField)
    {
        if (textField.getText().isEmpty())
        {
            return false;
        } else
        {
            return true;
        }
    }

//    public void dataPanel(Object obj)
//    {
//        claveTextField.setText(Integer.toString(((Carrera) obj).getCve()));
//        nomTextField.setText(((Carrera) obj).getNombre());
//        jefeTextField.setText(((Carrera) obj).getJefe());
//    }
    public static Nodo buscar(Nodo raiz, int nivel, String[] etiqueta)
    {
        if (nivel == etiqueta.length - 1)
        {
            Nodo aux1 = busca(raiz, etiqueta[nivel]);
            if (aux1 != null)
            {
                System.out.println(aux1.getEtiqueta());
            }
            return aux1;
        } else
        {
            Nodo aux = busca(raiz, etiqueta[nivel]);
            if (aux == null)
            {
                System.out.println("No encontre el dato: " + etiqueta[nivel] + " del nivel " + nivel);
                return raiz;
            } else
            {

                return buscar(aux.getAbj(), nivel + 1, etiqueta);
            }
        }
    }

    public String desp0(Nodo raiz, int nivel)
    {
        String s = "";
        if (raiz != null)
        {
            s = raiz.getEtiqueta();
            insComboBox.addItem(s);
            desp0(raiz.getSig(), 0);
        }
        return s;
    }

    public void actualizarUI()
    {
        GuardaArchivos.guardar(Principal.raiz, "Multilista.dat");
        desp0(Principal.raiz, 0);

    }

    public static void cambia(Object obj)
    {
        habilita(true, obj);
        if (obj instanceof JDateChooser)
        {
            ((JDateChooser) obj).requestFocus();
        }
    }

    public static void habilita(boolean b, Object obj)
    {

        if (obj instanceof JDateChooser)
        {
            ((JDateChooser) obj).setEnabled(b);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AgregarReun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AgregarReun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AgregarReun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AgregarReun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AgregarReun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar1;
    private javax.swing.JButton aceptarButton;
    private javax.swing.JPanel agregarPanel;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JComboBox<String> carComboBox;
    private com.toedter.calendar.JDateChooser fechaCalendar;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel flioLabel;
    private javax.swing.JTextField folTextField;
    private javax.swing.JComboBox<String> insComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel motLabel;
    private javax.swing.JTextField motTextField;
    // End of variables declaration//GEN-END:variables

}
