package Clases;
import static Clases.Principal.buscar;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import listas.Multilistas;
import listas.Nodo;
import proyu3u4.AgregaIns;

/**
 *
 * @author Daniel Castrejon
 */
public class AgregarINs extends javax.swing.JFrame
{

    /**
     * Creates new form VentanaAgregaIns
     */
    public AgregarINs()
    {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/tecnm.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton2 = new javax.swing.JButton();
        dirTextField = new javax.swing.JTextField();
        cveInstitucionLabel = new javax.swing.JLabel();
        cveTextField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nomTextField = new javax.swing.JTextField();
        telLabel = new javax.swing.JLabel();
        telTextField = new javax.swing.JTextField();
        atrasButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dirLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tecnologico Nacional de Mexico");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Menu Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 220, 50));

        dirTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        dirTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dirTextFieldActionPerformed(evt);
            }
        });
        dirTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                dirTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                dirTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(dirTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 230, 30));

        cveInstitucionLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cveInstitucionLabel.setForeground(new java.awt.Color(255, 255, 255));
        cveInstitucionLabel.setText("Clave Institucion:");
        getContentPane().add(cveInstitucionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        cveTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cveTextField.setEnabled(false);
        cveTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cveTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cveTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(cveTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 230, 30));

        nombreLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("Nombre:");
        getContentPane().add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        nomTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        nomTextField.setEnabled(false);
        nomTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(nomTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 230, 30));

        telLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        telLabel.setForeground(new java.awt.Color(255, 255, 255));
        telLabel.setText("Telefono:");
        getContentPane().add(telLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        telTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        telTextField.setEnabled(false);
        telTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                telTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                telTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(telTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 230, 30));

        atrasButton.setBackground(new java.awt.Color(153, 153, 153));
        atrasButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        atrasButton.setForeground(new java.awt.Color(255, 255, 255));
        atrasButton.setText("Cancelar");
        atrasButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                atrasButtonActionPerformed(evt);
            }
        });
        atrasButton.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                atrasButtonKeyPressed(evt);
            }
        });
        getContentPane().add(atrasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 150, 50));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 150, 50));

        agregarButton.setBackground(new java.awt.Color(153, 153, 153));
        agregarButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        agregarButton.setForeground(new java.awt.Color(255, 255, 255));
        agregarButton.setText("Agregar");
        agregarButton.setEnabled(false);
        agregarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                agregarButtonActionPerformed(evt);
            }
        });
        agregarButton.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                agregarButtonKeyPressed(evt);
            }
        });
        getContentPane().add(agregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 150, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO_TECNM_BLANCO (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar Institucion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        dirLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dirLabel.setForeground(new java.awt.Color(255, 255, 255));
        dirLabel.setText("Director:");
        getContentPane().add(dirLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura-madera-en-negro_2560x1600_xtrafondos.com.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_agregarButtonActionPerformed
    {//GEN-HEADEREND:event_agregarButtonActionPerformed
        try
        {
            AgregaIns ins = new AgregaIns("", 0, "", 0);
            Object objInst = ins.datos(dirTextField.getText(), Integer.parseInt(cveTextField.getText()), nomTextField.getText(), Integer.parseInt(telTextField.getText()));
            Nodo p = new Nodo(objInst, nomTextField.getText());
            String etiqueta[] = new String[1];
            etiqueta[0] = nomTextField.getText();
            Nodo n1 = buscar(Principal.raiz, 0, etiqueta);
            Nodo ex = buscar(Principal.raiz, 0, etiqueta);
            if (n1 != null && ex != null)
            {
                if (n1.getEtiqueta().equalsIgnoreCase(ex.getEtiqueta()))
                {
                    JOptionPane.showMessageDialog(null, "Institucion ya resgistrada con el mismo nombre");
                } else
                {
                    JOptionPane.showMessageDialog(null, "Institución agregada");
                    Principal.raiz = Multilistas.insertar(Principal.raiz, p, 0, etiqueta, null);
                    dirTextField.setText("");
                    CtrlInterfaz.habilita(false, cveTextField);
                    cveTextField.setText("");
                    CtrlInterfaz.habilita(false, nomTextField);
                    nomTextField.setText("");
                    telTextField.setText("");
                    CtrlInterfaz.habilita(false, telTextField);
                    CtrlInterfaz.cambia(dirTextField);
                }
            } else
            {
                JOptionPane.showMessageDialog(null, "Institución agregada");
                Principal.raiz = Multilistas.insertar(Principal.raiz, p, 0, etiqueta, null);
                dirTextField.setText("");
                CtrlInterfaz.habilita(false, cveTextField);
                cveTextField.setText("");
                CtrlInterfaz.habilita(false, nomTextField);
                nomTextField.setText("");
                telTextField.setText("");
                CtrlInterfaz.habilita(false, telTextField);
                CtrlInterfaz.cambia(dirTextField);
            }

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, " Error !!!\n" + " Intente de nuevo");
        }
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void agregarButtonKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_agregarButtonKeyPressed
    {//GEN-HEADEREND:event_agregarButtonKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            agregarButtonActionPerformed(null);
        }
    }//GEN-LAST:event_agregarButtonKeyPressed

    private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_atrasButtonActionPerformed
    {//GEN-HEADEREND:event_atrasButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Los cambios no Guardados se perderan", "ATENCION", JOptionPane.WARNING_MESSAGE);
        MI v = new MI();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasButtonActionPerformed

    private void atrasButtonKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_atrasButtonKeyPressed
    {//GEN-HEADEREND:event_atrasButtonKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            atrasButtonActionPerformed(null);
        }
    }//GEN-LAST:event_atrasButtonKeyPressed

    private void dirTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_dirTextFieldKeyPressed
    {//GEN-HEADEREND:event_dirTextFieldKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (validarCVacio(dirTextField))
            {
                CtrlInterfaz.cambia(cveTextField);
            } else
            {
                JOptionPane.showMessageDialog(this, "No puede dejar este campo vacio", "ATENCION", JOptionPane.WARNING_MESSAGE);
                dirTextField.requestFocus();
            }
        }
    }//GEN-LAST:event_dirTextFieldKeyPressed

    private void cveTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveTextFieldKeyTyped
    {//GEN-HEADEREND:event_cveTextFieldKeyTyped
        Validaciones.validaEntero(evt, 7, cveTextField.getText());
    }//GEN-LAST:event_cveTextFieldKeyTyped

    private void telTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telTextFieldKeyTyped
    {//GEN-HEADEREND:event_telTextFieldKeyTyped
        Validaciones.validaEntero(evt, 9, telTextField.getText());
    }//GEN-LAST:event_telTextFieldKeyTyped

    private void cveTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cveTextFieldKeyPressed
    {//GEN-HEADEREND:event_cveTextFieldKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (validarCVacio(cveTextField))
            {
                CtrlInterfaz.cambia(nomTextField);
            } else
            {
                JOptionPane.showMessageDialog(this, "No puede dejar este campo vacio", "ATENCION", JOptionPane.WARNING_MESSAGE);
                cveTextField.requestFocus();
            }
        }
    }//GEN-LAST:event_cveTextFieldKeyPressed

    private void dirTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_dirTextFieldKeyTyped
    {//GEN-HEADEREND:event_dirTextFieldKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_dirTextFieldKeyTyped

    private void nomTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomTextFieldKeyPressed
    {//GEN-HEADEREND:event_nomTextFieldKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (validarCVacio(nomTextField))
            {
                CtrlInterfaz.cambia(telTextField);
            } else
            {
                JOptionPane.showMessageDialog(this, "No puede dejar este campo vacio", "ATENCION", JOptionPane.WARNING_MESSAGE);
                nomTextField.requestFocus();
            }
        }
    }//GEN-LAST:event_nomTextFieldKeyPressed

    private void nomTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomTextFieldKeyTyped
    {//GEN-HEADEREND:event_nomTextFieldKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_nomTextFieldKeyTyped

    private void telTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_telTextFieldKeyPressed
    {//GEN-HEADEREND:event_telTextFieldKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (validarCVacio(telTextField))
            {
                CtrlInterfaz.cambia(agregarButton);
            } else
            {
                JOptionPane.showMessageDialog(this, "No puede dejar este campo vacio", "ATENCION", JOptionPane.WARNING_MESSAGE);
                telTextField.requestFocus();
            }
        }
    }//GEN-LAST:event_telTextFieldKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Principal v = new Principal();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        dirTextField.setText("");
        dirTextField.requestFocus();
        CtrlInterfaz.habilita(false, cveTextField);
        cveTextField.setText("");
        CtrlInterfaz.habilita(false, nomTextField);
        nomTextField.setText("");
        CtrlInterfaz.habilita(false, telTextField);
        telTextField.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dirTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dirTextFieldActionPerformed
    {//GEN-HEADEREND:event_dirTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Los cambios no Guardados se perderan", "ATENCION", JOptionPane.WARNING_MESSAGE);
        Principal pri=new Principal();
        pri.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void habilitar(JTextField textfield, java.awt.event.KeyEvent evt, JTextField textfield1)
    {
        if (evt.getKeyChar() == '\n' && validarCVacio(textfield1))
        {
            textfield.setEnabled(true);
            textfield.requestFocus();
        }
    }

    public void habilitarButton(java.awt.event.KeyEvent evt, JButton jbutton, JTextField textfield)
    {
        if (evt.getKeyChar() == '\n' && validarCVacio(textfield))
        {
            jbutton.setEnabled(true);
            jbutton.requestFocus();
        }
    }

    public void validarInt(java.awt.event.KeyEvent evt)
    {
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
            evt.consume();  // ignorar el evento de teclado
        }
    }

    public void validarStr(java.awt.event.KeyEvent evt)
    {
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if (!Character.isLetter(caracter))
        {
            evt.consume();  // ignorar el evento de teclado
        }

    }

    public boolean validarCVacio(JTextField textField)
    {
        if (textField.getText().isEmpty())
        {
            return false;
        } else
        {
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AgregarINs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AgregarINs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AgregarINs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AgregarINs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AgregarINs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton atrasButton;
    private javax.swing.JLabel cveInstitucionLabel;
    private javax.swing.JTextField cveTextField;
    private javax.swing.JLabel dirLabel;
    private javax.swing.JTextField dirTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomTextField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel telLabel;
    private javax.swing.JTextField telTextField;
    // End of variables declaration//GEN-END:variables

}
