package Clases;

import static Clases.AgregarCarr.buscar;
import arbolbin.ArbolBinario;
import arbolbin.NodoArbol;
import arbolbin.TablasHash;
import cjb.ci.CtrlInterfaz;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import listas.GuardaArchivos;
import listas.ListaSL;
import listas.Multilistas;
import static listas.Multilistas.busca;
import listas.Nodo;
import proyu3u4.Carrera;

/**
 *
 * @author Daniel Alberto Hernandez Castrejon
 * @author Humberto Gonzalez Garduño
 * @author Oscar Lopez Fonseca
 */
public class CamboCarr extends javax.swing.JFrame
{

    String label[] = new String[2];
    public static String tecAct = "";
    public static String tecDes = "";

    /**
     * Creates new form VentanaCambio
     */
    public CamboCarr()
    {
        initComponents();
        actualizarUI();
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/tecnm.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel3 = new javax.swing.JLabel();
        tecActualLabel = new javax.swing.JLabel();
        tecActComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        carreraComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tecDesComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        cambiarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cvaLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        bossLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        nvoTecLabel = new javax.swing.JLabel();
        cvaTextField = new javax.swing.JTextField();
        nomTextField = new javax.swing.JTextField();
        bossTextField = new javax.swing.JTextField();
        tecActTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cambiar Carrera");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        tecActualLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tecActualLabel.setForeground(new java.awt.Color(255, 255, 255));
        tecActualLabel.setText("TECNOLOGICO ACTUAL");
        getContentPane().add(tecActualLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 220, -1));

        tecActComboBox.setBackground(new java.awt.Color(153, 153, 153));
        tecActComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tecActComboBox.setForeground(new java.awt.Color(255, 255, 255));
        tecActComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        tecActComboBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                tecActComboBoxItemStateChanged(evt);
            }
        });
        tecActComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tecActComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(tecActComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 190, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CARRERA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 100, -1));

        carreraComboBox.setBackground(new java.awt.Color(153, 153, 153));
        carreraComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        carreraComboBox.setForeground(new java.awt.Color(255, 255, 255));
        carreraComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        carreraComboBox.setEnabled(false);
        carreraComboBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                carreraComboBoxItemStateChanged(evt);
            }
        });
        carreraComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                carreraComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(carreraComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 130, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TECNOLÓGICO DESTINO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 230, -1));

        tecDesComboBox.setBackground(new java.awt.Color(153, 153, 153));
        tecDesComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tecDesComboBox.setForeground(new java.awt.Color(255, 255, 255));
        tecDesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        tecDesComboBox.setEnabled(false);
        tecDesComboBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                tecDesComboBoxItemStateChanged(evt);
            }
        });
        tecDesComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tecDesComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(tecDesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 217, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Menu Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 180, 40));

        cambiarButton.setBackground(new java.awt.Color(153, 153, 153));
        cambiarButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cambiarButton.setForeground(new java.awt.Color(255, 255, 255));
        cambiarButton.setText("Cambiar");
        cambiarButton.setEnabled(false);
        cambiarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cambiarButtonActionPerformed(evt);
            }
        });
        cambiarButton.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cambiarButtonKeyPressed(evt);
            }
        });
        getContentPane().add(cambiarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO_TECNM_BLANCO (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cvaLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cvaLabel.setForeground(new java.awt.Color(255, 255, 255));
        cvaLabel.setText("Clave:");
        getContentPane().add(cvaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        nomLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nomLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomLabel.setText("Carrera:");
        getContentPane().add(nomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 160, -1));

        bossLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bossLabel.setForeground(new java.awt.Color(255, 255, 255));
        bossLabel.setText("Jefe:");
        getContentPane().add(bossLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 130, 40));

        nvoTecLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nvoTecLabel.setForeground(new java.awt.Color(255, 255, 255));
        nvoTecLabel.setText("Nuevo Tecnologico:");
        getContentPane().add(nvoTecLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 210, -1));

        cvaTextField.setEnabled(false);
        getContentPane().add(cvaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 305, -1));

        nomTextField.setEnabled(false);
        nomTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nomTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 305, -1));

        bossTextField.setEnabled(false);
        getContentPane().add(bossTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 305, -1));

        tecActTextField.setEnabled(false);
        getContentPane().add(tecActTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 305, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura-madera-en-negro_2560x1600_xtrafondos.com.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tecActComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tecActComboBoxActionPerformed
    {//GEN-HEADEREND:event_tecActComboBoxActionPerformed

    }//GEN-LAST:event_tecActComboBoxActionPerformed

    private void cambiarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cambiarButtonActionPerformed
    {//GEN-HEADEREND:event_cambiarButtonActionPerformed
        try
        {
            String etiqueta1[] = new String[2];
            etiqueta1[0] = tecAct;
            etiqueta1[1] = carreraComboBox.getSelectedItem().toString();
            Nodo aux2 = buscar(Principal.raiz, 0, etiqueta1);
            //EXTRAER EL ARBOL DE LA POSICION INDICADA EN LA TABLA HASH
            ArbolBinario ab = new ArbolBinario();
            ab = TablasHash.buscar(Principal.rHash, aux2.getEtiqueta(), null);
            ArbolBinario abc = new ArbolBinario();
            //NODOARBOL QUE CONTIENE EN SU HILO EL NODOLISTA BUSCADO
            NodoArbol nab = null;
            nab = abc.buscar(ab.getRaiz(), aux2.getEtiqueta().toLowerCase(), 0, aux2, nab);
            Principal.s = Multilistas.elimina(Principal.raiz, 0, etiqueta1);
            Principal.raiz = Principal.s[0];
            if (Principal.s[1] == null)
            {
                JOptionPane.showMessageDialog(null, "Datos no válidos");

            } else
            {
                Nodo c = Principal.s[1];
                String etiqueta[] = new String[2];
                etiqueta[0] = tecDes;
                etiqueta[1] = carreraComboBox.getSelectedItem().toString();
                Nodo n1 = buscar(Principal.raiz, 0, etiqueta);
                Nodo ex = buscar(Principal.raiz, 0, etiqueta);
                Nodo aux = Multilistas.busca(Principal.raiz, etiqueta1[0]);
                Nodo aux1 = Multilistas.busca(Principal.raiz, etiqueta[0]);
                if (n1 != null && ex != null)
                {
                    if (n1.getEtiqueta().equalsIgnoreCase(ex.getEtiqueta()))
                    {
                        JOptionPane.showMessageDialog(null, "Carrera ya resgistrada con el mismo nombre");
                        Principal.raiz = Multilistas.insertar(Principal.raiz, c, 0, etiqueta1, aux);
                        //SE QUEDA CON EL MISMO HILO
                        nab.setHilo(null);
                        nab.setHilo(c);
                        tecActTextField.setText(tecAct);
                        System.out.println("Conector arriba: " + c.getArb().getEtiqueta());
                    } else
                    {
                        Principal.raiz = Multilistas.insertar(Principal.raiz, c, 0, etiqueta, aux1);
                        //SE CAMBIA EL HILO
                        nab.setHilo(null);
                        nab.setHilo(c);
                        tecActTextField.setText(tecDes);
                        System.out.println("Conector arriba: " + c.getArb().getEtiqueta());
                    }
                } else
                {
                    Principal.raiz = Multilistas.insertar(Principal.raiz, c, 0, etiqueta, aux1);
                    //SE CAMBIA EL HILO
                    nab.setHilo(null);
                    nab.setHilo(c);
                    tecActTextField.setText(tecDes);
                    System.out.println("Conector arriba: " + c.getArb().getEtiqueta());
                }
            }
            carreraComboBox.removeAllItems();
            carreraComboBox.addItem("Seleccione");
            UpdateUI(Principal.raiz, UpdateLabel(tecAct), 0);
            dataPanel(Principal.s[1].getObj());
            CtrlInterfaz.habilita(false, carreraComboBox);
            CtrlInterfaz.habilita(false, tecDesComboBox);
            CtrlInterfaz.habilita(false, cambiarButton);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, " Error !!!\n" + " Intente de nuevo");
        }

    }//GEN-LAST:event_cambiarButtonActionPerformed

    private void tecDesComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tecDesComboBoxActionPerformed
    {//GEN-HEADEREND:event_tecDesComboBoxActionPerformed

    }//GEN-LAST:event_tecDesComboBoxActionPerformed

    private void cambiarButtonKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cambiarButtonKeyPressed
    {//GEN-HEADEREND:event_cambiarButtonKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            cambiarButtonActionPerformed(null);
        }
    }//GEN-LAST:event_cambiarButtonKeyPressed

    private void tecActComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_tecActComboBoxItemStateChanged
    {//GEN-HEADEREND:event_tecActComboBoxItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            if (tecActComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione"))
            {
            } else
            {
                tecAct = tecActComboBox.getSelectedItem().toString();
                carreraComboBox.removeAllItems();
                carreraComboBox.addItem("Seleccione");
                UpdateUI(Principal.raiz, UpdateLabel(tecAct), 0);
                CtrlInterfaz.cambia(carreraComboBox);
            }
        }
    }//GEN-LAST:event_tecActComboBoxItemStateChanged

    private void carreraComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_carreraComboBoxItemStateChanged
    {//GEN-HEADEREND:event_carreraComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            if (carreraComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione"))
            {
                // JOptionPane.showMessageDialog(null, "Opcion Invalida");
            } else
            {
                CtrlInterfaz.cambia(tecDesComboBox);
            }
        }
    }//GEN-LAST:event_carreraComboBoxItemStateChanged

    private void tecDesComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_tecDesComboBoxItemStateChanged
    {//GEN-HEADEREND:event_tecDesComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            if (tecDesComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione"))
            {
                JOptionPane.showMessageDialog(null, "Opcion Invalida");
                CtrlInterfaz.habilita(false, cambiarButton);
            } else
            {
                tecDes = tecDesComboBox.getSelectedItem().toString();
                CtrlInterfaz.cambia(cambiarButton);
            }
        }
    }//GEN-LAST:event_tecDesComboBoxItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Principal v = new Principal();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void nomTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nomTextFieldActionPerformed
    {//GEN-HEADEREND:event_nomTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
    JOptionPane.showMessageDialog(this, "Los cambios no Guardados se perderan", "ATENCION", JOptionPane.WARNING_MESSAGE);  
    Principal v = new Principal();
        v.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void carreraComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_carreraComboBoxActionPerformed
    {//GEN-HEADEREND:event_carreraComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carreraComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
    JOptionPane.showMessageDialog(this, "Los cambios no Guardados se perderan", "ATENCION", JOptionPane.WARNING_MESSAGE);
    MC mrc=new MC();
    mrc.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    public void UpdateUI(Nodo raiz, String[] etiqueta, int nivel)
    {
        if (nivel == etiqueta.length - 1)
        {
            Nodo aux = raiz;
            String s = "";
            while (aux != null)
            {
                s = aux.getEtiqueta();
                carreraComboBox.addItem(s);
                aux = aux.getSig();
            }
        } else
        {
            Nodo aux = busca(raiz, etiqueta[nivel]);
            if (aux == null)
            {
                System.out.println("NO HAY REUNIONES");

            } else
            {
                UpdateUI(aux.getAbj(), etiqueta, nivel + 1);
            }
        }
        GuardaArchivos.guardar(raiz, "Multilista.dat");
    }

    public String[] UpdateLabel(String s)
    {
        label[0] = s;
        label[1] = "";
        return label;
    }

    public String desp0(Nodo raiz, int nivel)
    {
        String s = "";
        if (raiz != null)
        {
            s = raiz.getEtiqueta();
            tecActComboBox.addItem(s);
            tecDesComboBox.addItem(s);
            desp0(raiz.getSig(), 0);
        }
        return s;
    }

    public void actualizarUI()
    {
        desp0(Principal.raiz, 0);
    }

    public void dataPanel(Object obj)
    {
        cvaTextField.setText(Integer.toString(((Carrera) obj).getCve()));
        nomTextField.setText(((Carrera) obj).getNombre());
        bossTextField.setText(((Carrera) obj).getJefe());
    }

    public static Nodo buscar(Nodo raiz, int nivel, String[] etiqueta)
    {
        if (nivel == etiqueta.length - 1)
        {
            Nodo aux1 = busca(raiz, etiqueta[nivel]);
            if (aux1 != null)
            {
                System.out.println(aux1.getEtiqueta());
            }
            return aux1;
        } else
        {
            Nodo aux = busca(raiz, etiqueta[nivel]);
            if (aux == null)
            {
                System.out.println("No encontre el dato: " + etiqueta[nivel] + " del nivel " + nivel);
                return raiz;
            } else
            {

                return buscar(aux.getAbj(), nivel + 1, etiqueta);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CamboCarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CamboCarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CamboCarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CamboCarr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CamboCarr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bossLabel;
    private javax.swing.JTextField bossTextField;
    private javax.swing.JButton cambiarButton;
    public javax.swing.JComboBox<String> carreraComboBox;
    private javax.swing.JLabel cvaLabel;
    private javax.swing.JTextField cvaTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField nomTextField;
    private javax.swing.JLabel nvoTecLabel;
    private javax.swing.JComboBox<String> tecActComboBox;
    private javax.swing.JTextField tecActTextField;
    private javax.swing.JLabel tecActualLabel;
    private javax.swing.JComboBox<String> tecDesComboBox;
    // End of variables declaration//GEN-END:variables

}
