package Clases;

import static Clases.Principal.raiz;
import arbolbin.TablasHash;
import cjb.ci.CtrlInterfaz;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import listas.GuardaArchivos;
import listas.ListaSL;
import listas.Multilistas;
import static listas.Multilistas.busca;
import listas.Nodo;

/**
 *
 * @author Daniel Castrejon
 */
public class ElimiaIns extends javax.swing.JFrame
{

    /**
     * Creates new form VtnEliminacionIns
     */
    public ElimiaIns()
    {
        initComponents();
        actualizarUI();
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/tecnm.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        elimLabel = new javax.swing.JLabel();
        Cancelar1 = new javax.swing.JButton();
        tecElimComboBox = new javax.swing.JComboBox<>();
        Cancelar = new javax.swing.JButton();
        elimButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        elimLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        elimLabel.setForeground(new java.awt.Color(255, 255, 255));
        elimLabel.setText("Seleccione la Institución");
        getContentPane().add(elimLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 290, -1));

        Cancelar1.setBackground(new java.awt.Color(153, 153, 153));
        Cancelar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Cancelar1.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar1.setText("Menu Principal");
        Cancelar1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Cancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 230, 40));

        tecElimComboBox.setBackground(new java.awt.Color(102, 102, 102));
        tecElimComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tecElimComboBox.setForeground(new java.awt.Color(255, 255, 255));
        tecElimComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        tecElimComboBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                tecElimComboBoxItemStateChanged(evt);
            }
        });
        tecElimComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tecElimComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(tecElimComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 280, 30));

        Cancelar.setBackground(new java.awt.Color(153, 153, 153));
        Cancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 240, 50));

        elimButton.setBackground(new java.awt.Color(153, 153, 153));
        elimButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        elimButton.setForeground(new java.awt.Color(255, 255, 255));
        elimButton.setText("Eliminar");
        elimButton.setToolTipText("");
        elimButton.setEnabled(false);
        elimButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                elimButtonActionPerformed(evt);
            }
        });
        elimButton.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                elimButtonKeyPressed(evt);
            }
        });
        getContentPane().add(elimButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 240, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO_TECNM_BLANCO (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 37)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Eliminar Carrera");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura-madera-en-negro_2560x1600_xtrafondos.com.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void elimButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_elimButtonActionPerformed
    {//GEN-HEADEREND:event_elimButtonActionPerformed
        try
        {
            if (tecElimComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || tecElimComboBox.getSelectedItem().toString().equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(this, "Opcion Invalida");
            } else
            {
                String etiqueta1[] = new String[1];
                etiqueta1[0] = tecElimComboBox.getSelectedItem().toString();
                String etq[] = new String[2];
                etq[0]=tecElimComboBox.getSelectedItem().toString();
                ListaSL ls = BuscarCarreras(Principal.raiz,etq,0);
                eliminarDArbol(ls);
                Principal.s = Multilistas.elimina(Principal.raiz, 0, etiqueta1);
                Principal.raiz = Principal.s[0];
                JOptionPane.showMessageDialog(null, "Institucion eliminada");
                /*tecElimComboBox.removeAllItems();
                tecElimComboBox.addItem("Seleccione");
                actualizarUI();*/
                Principal v = new Principal();
                v.setVisible(true);
                this.dispose();

            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }//GEN-LAST:event_elimButtonActionPerformed

    private void elimButtonKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_elimButtonKeyPressed
    {//GEN-HEADEREND:event_elimButtonKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            elimButtonActionPerformed(null);
        }
    }//GEN-LAST:event_elimButtonKeyPressed

    private void tecElimComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_tecElimComboBoxItemStateChanged
    {//GEN-HEADEREND:event_tecElimComboBoxItemStateChanged
      if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            if (tecElimComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || tecElimComboBox.getSelectedItem().toString().equalsIgnoreCase(""))
            {
                //deshabilitaButton(elimButton);
                CtrlInterfaz.habilita(false, elimButton);
            } else
            {
                CtrlInterfaz.habilita(true, elimButton);
                //habilitarButton(elimButton);
            }
        }
    }//GEN-LAST:event_tecElimComboBoxItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Principal v = new Principal();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelarActionPerformed
    {//GEN-HEADEREND:event_CancelarActionPerformed
       JOptionPane.showMessageDialog(this, "Los cambios no Guardados se perderan", "ATENCION", JOptionPane.WARNING_MESSAGE);
       MI v = new MI();
        v.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed

    private void tecElimComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tecElimComboBoxActionPerformed
    {//GEN-HEADEREND:event_tecElimComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tecElimComboBoxActionPerformed

    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Cancelar1ActionPerformed
    {//GEN-HEADEREND:event_Cancelar1ActionPerformed
        // TODO add your handling code here:
    JOptionPane.showMessageDialog(this, "Los cambios no Guardados se perderan", "ATENCION", JOptionPane.WARNING_MESSAGE);
    Principal v = new Principal();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Cancelar1ActionPerformed
    public String desp0(Nodo raiz, int nivel)
    {
        String s = "";
        if (raiz != null)
        {
            s = raiz.getEtiqueta();
            tecElimComboBox.addItem(s);
            desp0(raiz.getSig(), 0);
        }
        return s;
    }

    public void actualizarUI()
    {
        GuardaArchivos.guardar(Principal.raiz, "Multilista.dat");
        desp0(Principal.raiz, 0);
    }

    public void habilitarButton(JButton jbutton)
    {
        jbutton.setEnabled(true);
        jbutton.requestFocus();
    }

    public void deshabilitaButton(JButton jbutton)
    {
        jbutton.setEnabled(false);
        //jbutton.requestFocus();
    }

    public ListaSL BuscarCarreras(Nodo raiz, String[] etiqueta, int nivel)
    {
        if (nivel == etiqueta.length - 1)
        {
            Nodo aux = raiz;
            String s = "";
            ListaSL ls = new ListaSL();
            ls.setRaiz(raiz);
            return ls;

        } else
        {
            Nodo aux = busca(raiz, etiqueta[nivel]);
            if (aux == null)
            {
                System.out.println("NO HAY REUNIONES");
                return null;
            } else
            {
                return BuscarCarreras(aux.getAbj(), etiqueta, nivel + 1);
            }
        }
    }

    public void eliminarDArbol(ListaSL ls)
    {
        if (ls.getRaiz() == null)
        {
            System.out.println("NO TIENE CARRERAS");
        } else
        {
            Nodo aux = ls.getRaiz();
            while (aux != null)
            {
                Principal.rHash = TablasHash.elimina(Principal.rHash, aux.getEtiqueta().toLowerCase(), aux);
                aux = aux.getSig();
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ElimiaIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ElimiaIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ElimiaIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ElimiaIns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ElimiaIns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Cancelar1;
    private javax.swing.JButton elimButton;
    private javax.swing.JLabel elimLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> tecElimComboBox;
    // End of variables declaration//GEN-END:variables
class FondoPanelg extends JPanel
    {

        private Image imagen;

        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondog.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    class FondoPanelp extends JPanel
    {

        private Image imagen;

        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondop.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
