/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academia;

import arbolesylistas.GuardaArchivos;
import arbolesylistas.Multilistas;
import static arbolesylistas.Multilistas.busca;
import arbolesylistas.Nodo;
import cjb.ci.CtrlInterfaz;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Daniel Castrejon
 */
public class VtnEliminaR extends javax.swing.JFrame
{

    String label[] = new String[2];
    String label1[] = new String[3];

    /**
     * Creates new form VtnEliminaR
     */
    public VtnEliminaR()
    {
        initComponents();
        actualizarUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new FondoPanelp();
        fechaElimLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EliminarButton = new javax.swing.JButton();
        reuElimComboBox = new javax.swing.JComboBox<>();
        fechaElimLabel1 = new javax.swing.JLabel();
        fechaElimLabel2 = new javax.swing.JLabel();
        insComboBox = new javax.swing.JComboBox<>();
        carComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminacion de Reunion");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        fechaElimLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        fechaElimLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaElimLabel.setText("FOLIO");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ELIMINAR REUNION CON FOLIO");

        EliminarButton.setText("Eliminar");
        EliminarButton.setEnabled(false);
        EliminarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EliminarButtonActionPerformed(evt);
            }
        });
        EliminarButton.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                EliminarButtonKeyPressed(evt);
            }
        });

        reuElimComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        reuElimComboBox.setEnabled(false);
        reuElimComboBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                reuElimComboBoxItemStateChanged(evt);
            }
        });

        fechaElimLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        fechaElimLabel1.setForeground(new java.awt.Color(255, 255, 255));
        fechaElimLabel1.setText("INSTITUCION");

        fechaElimLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        fechaElimLabel2.setForeground(new java.awt.Color(255, 255, 255));
        fechaElimLabel2.setText("CARRERA");

        insComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        insComboBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                insComboBoxItemStateChanged(evt);
            }
        });

        carComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        carComboBox.setEnabled(false);
        carComboBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                carComboBoxItemStateChanged(evt);
            }
        });

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EliminarButton)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fechaElimLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaElimLabel1)
                            .addComponent(fechaElimLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(carComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(reuElimComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaElimLabel1)
                    .addComponent(insComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaElimLabel2)
                    .addComponent(carComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaElimLabel)
                    .addComponent(reuElimComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarButton)
                    .addComponent(jButton1))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EliminarButtonActionPerformed
    {//GEN-HEADEREND:event_EliminarButtonActionPerformed
        try
        {
            if (reuElimComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || reuElimComboBox.getSelectedItem().toString().equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(null, "Opcion Invalida");
            } else
            {
                String etiqueta1[] = new String[3];
                etiqueta1[0] = insComboBox.getSelectedItem().toString();
                etiqueta1[1] = carComboBox.getSelectedItem().toString();
                etiqueta1[2] = reuElimComboBox.getSelectedItem().toString();
                VentanaP.s = Multilistas.elimina(VentanaP.raiz, 0, etiqueta1);
                VentanaP.raiz = VentanaP.s[0];
                reuElimComboBox.removeAllItems();
                reuElimComboBox.addItem("Seleccione");
                UpdateUI(VentanaP.raiz, etiqueta1, 0, reuElimComboBox);
                if (VentanaP.s[1] == null)
                {
                    JOptionPane.showMessageDialog(null, "Reunion no encontrada");

                } else
                {
                    JOptionPane.showMessageDialog(null, "Reunion eliminada");
                }

                reuElimComboBox.removeAllItems();
                reuElimComboBox.addItem("Seleccione");
                UpdateUI(VentanaP.raiz, etiqueta1, 0, reuElimComboBox);
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, " Error !!!\n" + " Intente de nuevo");
        }
    }//GEN-LAST:event_EliminarButtonActionPerformed

    private void EliminarButtonKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_EliminarButtonKeyPressed
    {//GEN-HEADEREND:event_EliminarButtonKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            EliminarButtonActionPerformed(null);
        }
    }//GEN-LAST:event_EliminarButtonKeyPressed

    private void insComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_insComboBoxItemStateChanged
    {//GEN-HEADEREND:event_insComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            if (insComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || insComboBox.getSelectedItem().toString().equalsIgnoreCase(""))
            {
                CtrlInterfaz.habilita(false, carComboBox);
            } else
            {
                CtrlInterfaz.cambia(carComboBox);
                Nodo aux = Multilistas.busca(VentanaP.raiz, insComboBox.getSelectedItem().toString());
                carComboBox.removeAllItems();
                carComboBox.addItem("Seleccione");
                UpdateUI(aux, UpdateLabel(aux.getEtiqueta()), 0, carComboBox);
            }
        }
    }//GEN-LAST:event_insComboBoxItemStateChanged

    private void carComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_carComboBoxItemStateChanged
    {//GEN-HEADEREND:event_carComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            if (carComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || carComboBox.getSelectedItem().toString().equalsIgnoreCase(""))
            {
                CtrlInterfaz.habilita(false, reuElimComboBox);
            } else
            {
                CtrlInterfaz.cambia(reuElimComboBox);
                Nodo aux = Multilistas.busca(VentanaP.raiz, insComboBox.getSelectedItem().toString());
                reuElimComboBox.removeAllItems();
                reuElimComboBox.addItem("Seleccione");
                UpdateUI(VentanaP.raiz, UpdateLabel(aux.getEtiqueta(), carComboBox.getSelectedItem().toString()), 0, reuElimComboBox);
            }
        }
    }//GEN-LAST:event_carComboBoxItemStateChanged

    private void reuElimComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_reuElimComboBoxItemStateChanged
    {//GEN-HEADEREND:event_reuElimComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            if (reuElimComboBox.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || reuElimComboBox.getSelectedItem().toString().equalsIgnoreCase(""))
            {
                CtrlInterfaz.habilita(false, EliminarButton);
            } else
            {
                CtrlInterfaz.cambia(EliminarButton);
            }
        }
    }//GEN-LAST:event_reuElimComboBoxItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        VentanaP v = new VentanaP();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        VentanaP v = new VentanaP();
        v.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void UpdateUI(Nodo raiz, String[] etiqueta, int nivel, JComboBox comboBox)
    {
        if (nivel == etiqueta.length - 1)
        {
            Nodo aux = raiz;
            String s = "";
            while (aux != null)
            {
                s = aux.getEtiqueta();
                comboBox.addItem(s);
                aux = aux.getSig();
            }
        } else
        {
            Nodo aux = busca(raiz, etiqueta[nivel]);
            if (aux == null)
            {
                System.out.println("NO HAY REUNIONES");
            } else
            {
                UpdateUI(aux.getAbj(), etiqueta, nivel + 1, comboBox);
            }
        }
//        GuardaArchivos.guardar(raiz, "Multilista.dat");
    }

    public String desp0(Nodo raiz, int nivel)
    {
        String s = "";
        if (raiz != null)
        {
            s = raiz.getEtiqueta();
            insComboBox.addItem(s);
            desp0(raiz.getSig(), 0);
        }
        return s;
    }

    public void actualizarUI()
    {
        GuardaArchivos.guardar(VentanaP.raiz, "Multilista.dat");
        desp0(VentanaP.raiz, 0);

    }

    public String[] UpdateLabel(String etq)
    {
        label[0] = etq;
        label[1] = "";
        return label;
    }

    public String[] UpdateLabel(String etq, String etq1)
    {
        label1[0] = etq;
        label1[1] = etq1;
        label1[2] = "";
        return label1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminaR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminaR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminaR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnEliminaR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnEliminaR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarButton;
    private javax.swing.JComboBox<String> carComboBox;
    private javax.swing.JLabel fechaElimLabel;
    private javax.swing.JLabel fechaElimLabel1;
    private javax.swing.JLabel fechaElimLabel2;
    private javax.swing.JComboBox<String> insComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> reuElimComboBox;
    // End of variables declaration//GEN-END:variables
class FondoPanelg extends JPanel
    {

        private Image imagen;

        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondog.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    class FondoPanelp extends JPanel
    {

        private Image imagen;

        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondop.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}

